### ISSUE TITLE
Change / disable background color for error highlighting

### ISSUE THREAD

**Issue by rnestler** [mh21/errormarker.vim#1]
With my color scheme the background color for errors leaves the text almost unreadable, especially the syntax highlighting is gone. Is it possible to change this color?

![errormarkers](https://cloud.githubusercontent.com/assets/1435346/14657702/99d4ae74-068f-11e6-9bbf-4422667104c4.png)

**Comment by mh21** [comment]
H Raphael,

you can change the highlighting groups as described in
https://github.com/mh21/errormarker.vim/blob/master/doc/errormarker.txt.
The default is

let errormarker_errorgroup = "ErrorMsg"
let errormarker_warninggroup = "Todo"

Cheers
  Michael

2016-04-20 0:34 GMT+02:00 Raphael Nestler notifications@github.com:
