### ISSUE TITLE
Support a command to remove all the signs.

### ISSUE THREAD

**Issue by skywind3000** [mh21/errormarker.vim#4]
support a command to remove all the signs which are belong to errormarker.vim:
I have to use this script in my vimrc to get signs removed:

```VimL
function! s:GuiSignRemove(...)
    if a:0 == 0 | return | endif
    redir => x
    silent sign place
    redir END
    let lines = split(x, '\n')
    for line in lines
        if line =~ '^\s*line=\d*\s*id=\d*\s*name='
            let name = matchstr(line, '^\s*line=.*name=\zs\w*')
            let id = matchstr(line, '^\s*line=\d*\s*id=\zs\w*')
            for x in range(a:0)
                if name == a:{x + 1}
                    silent exec 'sign unplace '.id
                endif
            endfor
        endif
    endfor
endfunc

command! -nargs=+ GuiSignRemove call s:GuiSignRemove(<f-args>)
noremap <silent><space>rm :GuiSignRemove errormarker_error errormarker_warning<cr>

```

could you please provide something like that directly in errormarker.vim ?
Some times when I am working on some old ugly .c file which is full of warnings or errors on modern 
compiler, I just want to tell errormarker: "thank you, I got it, could you please dissapear for a while, I want to refact this whole part of the source file, and the signs just get me distracted"

**Comment by mh21** [comment]
Thanks for the suggestion! I pushed a shorter version of the command as 66ab8e0a356ea8a971e99156c59d09c3beae5ef2, I hope that works for you.

**Comment by skywind3000** [comment]
It just works ! The tedious code could be removed now in my vimrc, thanks.

**Comment by skywind3000** [comment]
Welcome to use my plugin: [asyncrun](https://github.com/skywind3000/asyncrun.vim)
It now can cooperate with errormarker very well.
